name: 'labeled PR picker'
description: 'cheery-pick your labeled PR and create PR'
author: 'thaim'
branding:
  icon: 'git-pull-request'
  color: 'gray-dark'
inputs:
  token:
    description: 'github token'
    required: true
    default: ${{ github.token }}
  label-map:
    description: ''
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
